Implement large blobs
jcjones/u2f-hid-rs pull request #332
Opened 2024-02-08 15:29 UTC by msirringhaus

Implement basic writing and reading of large blob arrays associated with credentials.
Not yet supported: Stand-alone functions for updating (although that would be just reading, then writing), and Garbage collection.

Since we probably won't use this in Firefox right away, I have moved all operations that require more dependencies outside of the core and into the examples. In theory, we could all of that internally, but then we'd need AEAD-GCM and DEFLATE in the core.

2025-10-22 17:28 UTC, jschanck requested changes
Sorry for the wait on this one. Just a few comments below.

2025-10-22 17:28 UTC, jschanck commented on src/ctap2/commands/large_blobs.rs
> +        if input.is_empty() {
This should also error out if the input is length 1, otherwise we'll panic on `&input[1..]` below.

2025-10-22 17:28 UTC, jschanck commented on src/ctap2/commands/large_blobs.rs
> +                                from_slice(large_blob).unwrap();
We don't want to panic if the authenticator returns malformed data.

2025-10-22 17:28 UTC, jschanck commented on src/ctap2/commands/large_blobs.rs
> +        - 64;
Is there a guarantee that max_msg_size is greater than 64? We would need to error out if it is.

2025-10-22 17:28 UTC, jschanck commented on src/ctap2/commands/large_blobs.rs
> +        - 64;
As above, we need a consistency check here.

2025-10-23 11:25 UTC, msirringhaus commented on src/ctap2/commands/large_blobs.rs
> +        - 64;
I interpreted the spec as "it has to be 1024 or bigger", but the way it is worded does indeed allow for smaller max_msg_sizes. (Plus, we may just as well guard against non-compliant tokens)
> Likewise, because some authenticators are memory constrained, the maximum message size supported by an authenticator MAY be limited. By default, authenticators MUST support messages of at least 1024 bytes. Authenticators MAY declare a different maximum message size supported using the maxMsgSize authenticatorGetInfo result parameter.

I'll add a check and error out if it is smaller or equal to 64

2025-10-23 14:24 UTC, msirringhaus commented
Well, this was perfect timing if there ever was one. After all this time, `generic-array` pushed a 'broken' dot-release _last week_ that causes deprecation warnings to be emitted. I need to do a weird dance now by requesting the new generic-array-version in our `Cargo.toml` with a compat-feature flag on, as the `aes_gcm`-folks don't have a new version ready and try to do it only by the end of the year.
Luckily, all this is only in dev-dependencies (I could avoid the warning in the main code).

2025-10-23 15:29 UTC, merged